M48
; DRILL file {KiCad (6.0.1)} date Sat Jan  7 23:02:53 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-07T23:02:53-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X0.3406Y0.0797
X0.8819Y0.0797
X1.9252Y0.0797
T0
M30
